"""empty message

Revision ID: 15f2a1807992
Revises: e19c39da1be7
Create Date: 2022-01-04 10:59:49.029214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f2a1807992'
down_revision = 'e19c39da1be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('test', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
