"""empty message

Revision ID: 4a775207bf7f
Revises: 15f2a1807992
Create Date: 2022-01-04 11:00:31.211268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a775207bf7f'
down_revision = '15f2a1807992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'series')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('series', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
