"""empty message

Revision ID: 70d1fd63c0d3
Revises: 4a775207bf7f
Create Date: 2022-01-04 11:01:00.262585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d1fd63c0d3'
down_revision = '4a775207bf7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('series', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'series')
    # ### end Alembic commands ###
