"""empty message

Revision ID: e19c39da1be7
Revises: 374232e3a10c
Create Date: 2022-01-04 10:58:25.173267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19c39da1be7'
down_revision = '374232e3a10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('test', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'test')
    # ### end Alembic commands ###
